
@echo off

REM !!! Generated by the fmp-cli 1.88.0.  DO NOT EDIT!

md IntegrationBoard\Assets\3rd\fmp-xtc-integrationboard

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-integrationboard-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\IntegrationBoard\Assets\3rd\fmp-xtc-integrationboard\
